name: Build Geode Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android64:
    name: Build Android64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Geode mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: latest
          cli: latest
          configure-args: -DGEODE_PLATFORM=Android64

      - name: Upload Geode package
        uses: actions/upload-artifact@v4
        with:
          name: Geode-RPC-test-android64
          path: |
            build-android64/*.geode
            build-android64/**/*.geode
          if-no-files-found: error
